routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\ClassController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudyMajorController;
use App\Http\Controllers\TuitionController;
use App\Http\Middleware\Authenticate;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::view('/', 'pages.index')->middleware(['isStudent']);

Route::resource('tuitions', TuitionController::class)->middleware(['isEmployee']);
Route::resource('majors', StudyMajorController::class)->middleware(['isAdmin']);
Route::resource('classes', ClassController::class)->middleware(['isAdmin']);
Route::resource('students', StudentController::class)->middleware(['isAdmin']);

Route::controller(AuthController::class)->group(function () {
    Route::get('/auth/employee/login', 'loginEmployee')->name('auth.employee.login');
    Route::post('/auth/employee/login', 'authenticateEmployee')->name('auth.employee.authenticate');

    Route::get('/auth/login', 'loginStudent')->name('auth.student.login');
    Route::post('/auth/login', 'authenticateStudent')->name('auth.student.authenticate');

    Route::get('/auth/logout', 'logout')->name('auth.logout');
});

Route::controller(DashboardController::class)->group(function () {
    Route::get('/employee/dashboard', 'employeeIndex')->middleware(['isEmployee']);
    Route::get('/dashboard', 'index')->middleware(['isStudent'])->name('dashboard.student.index');
});

Route::post('/payments/{tuition}', [
    PaymentController::class,
    'acquireTransaction'
])->name('payments.acquire')->middleware(['isStudent']);

Route::post('/payments/{payment}/refresh', [
    PaymentController::class,
    'refreshTransaction'
])->name('payments.confirm')->middleware(['isStudent']);

resources/views/pages/majors/create.blade.php
@extends('layouts.app')

@section('title', 'Create Study Major')

@section('content')
    <x-container class="py-16">
        <h2 class="font-bold text-3xl">Creating Study Major</h2>
        <form method="post" class="w-full" action="{{ route('majors.store') }}">
            @csrf
            @method('POST')
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Study Major Name</span>
                </div>
                <input name="name" type="text" required value="{{ old('name') }}" placeholder="Software Engineering"
                    class="input input-bordered input-md w-full @error('name')
                        {{ 'input-error' }}
                    @enderror" />
                @error('name')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>
            <button type="submit" class="btn btn-primary w-full mt-4">Submit</button>
        </form>
    </x-container>
@endsection

resources/views/pages/majors/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Tuition')

@section('content')
    <x-container class="py-16">
        <h2 class="font-bold text-3xl">Updating Study Major</h2>
        <form method="post" class="w-full" action="{{ route('majors.update', $major->id) }}">
            @csrf
            @method('PATCH')
            <label class="form-control w-full">
                <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Study Major Name</span>
                </div>
                <input name="name" type="text" required value="{{ old('name') ?? $major->name }}" placeholder="Software Engineering"
                    class="input input-bordered input-md w-full @error('name')
                        {{ 'input-error' }}
                    @enderror" />
                @error('name')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>

            <button type="submit" class="btn btn-primary w-full mt-4">Update</button>
        </form>
    </x-container>
@endsection

resources/views/pages/majors/index.blade.php
@extends('layouts.app')

@section('title', 'School Study Majors')

@section('content')
    <x-container class="py-16 space-y-4">
        <h1 class="text-3xl font-bold">Manage Study Majors</h1>
        @if ($message = Session::get('success'))
            <div id="alertSession" role="alert" class="alert alert-success py-1">
                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none"
                    viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <span>{{ $message }}</span>
                <button class="btn btn-ghost rounded-full" onclick="document.getElementById('alertSession').remove()">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-x" width="16"
                        height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none"
                        stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                        <path d="M18 6l-12 12" />
                        <path d="M6 6l12 12" />
                    </svg></button>
            </div>
        @endif
        <div>
            <div class="w-full flex items-end">
                <a href="{{ route('majors.create') }}" class="ml-auto btn btn-sm btn-primary"><svg xmlns="http://www.w3.org/2000/svg"
                        class="icon icon-tabler icon-tabler-plus" width="14" height="14" viewBox="0 0 24 24"
                        stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                        <path d="M12 5l0 14" />
                        <path d="M5 12l14 0" />
                    </svg> New</a>
            </div>
            <div class="overflow-x-auto pb-8">
                <table class="table table-zebra">
                    <!-- head -->
                    <thead>
                        <tr class="text-center">
                            <th>No</th>
                            <th>Study Major Name</th>
                            <th>Enrolled Class</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $index = 0;
                        @endphp
                        @forelse ($majors as $major)
                            <tr class="text-center">
                                <th>{{ $index + 1 }}</th>
                                <td>{{ $major->name }}</td>
                                <td>{{ $major->classes()->count() }}</td>
                                <td>{{ date('d/m/Y', strtotime($major->created_at)) }}</td>
                                <td>
                                    <form method="post" action="{{ route('majors.destroy', $major->id) }}">
                                        @csrf
                                        @method('DELETE')
                                        <a role="button" href="{{ route('majors.edit', $major->id) }}"
                                            class="btn btn-sm btn-secondary">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-edit"
                                                width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5"
                                                stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                <path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1" />
                                                <path
                                                    d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z" />
                                                <path d="M16 5l3 3" />
                                            </svg>
                                        </a>
                                        <button type="submit" class="btn btn-sm btn-error">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash"
                                                width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5"
                                                stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                <path d="M4 7l16 0" />
                                                <path d="M10 11l0 6" />
                                                <path d="M14 11l0 6" />
                                                <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
                                                <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                                            </svg>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @php
                                $index++;
                            @endphp
                        @empty
                            <td colspan="6" class="text-center font-semibold text-lg py-4">No Data</td>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </x-container>
@endsection