routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\ClassController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudyMajorController;
use App\Http\Controllers\TuitionController;
use App\Http\Middleware\Authenticate;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::view('/', 'pages.index')->middleware(['isStudent']);

Route::resource('tuitions', TuitionController::class)->middleware(['isEmployee']);
Route::resource('majors', StudyMajorController::class)->middleware(['isAdmin']);
Route::resource('classes', ClassController::class)->middleware(['isAdmin']);
Route::resource('students', StudentController::class)->middleware(['isAdmin']);

Route::controller(AuthController::class)->group(function () {
    Route::get('/auth/employee/login', 'loginEmployee')->name('auth.employee.login');
    Route::post('/auth/employee/login', 'authenticateEmployee')->name('auth.employee.authenticate');

    Route::get('/auth/login', 'loginStudent')->name('auth.student.login');
    Route::post('/auth/login', 'authenticateStudent')->name('auth.student.authenticate');

    Route::get('/auth/logout', 'logout')->name('auth.logout');
});

Route::controller(DashboardController::class)->group(function () {
    Route::get('/employee/dashboard', 'employeeIndex')->middleware(['isEmployee']);
    Route::get('/dashboard', 'index')->middleware(['isStudent'])->name('dashboard.student.index');
});

Route::post('/payments/{tuition}', [
    PaymentController::class,
    'acquireTransaction'
])->name('payments.acquire')->middleware(['isStudent']);

Route::post('/payments/{payment}/refresh', [
    PaymentController::class,
    'refreshTransaction'
])->name('payments.confirm')->middleware(['isStudent']);

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * App\Models\Student
 *
 * @property int $id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string $nisn
 * @property string $nis
 * @property string $name
 * @property string $address
 * @property string $phone_number
 * @property int $class_id
 * @method static \Illuminate\Database\Eloquent\Builder|Student newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Student newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Student query()
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereAddress($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereClassId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereNis($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereNisn($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student wherePhoneNumber($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereUpdatedAt($value)
 * @property-read \App\Models\SchoolClass|null $studentClass
 * @property mixed $password
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection<int, \Illuminate\Notifications\DatabaseNotification> $notifications
 * @property-read int|null $notifications_count
 * @method static \Illuminate\Database\Eloquent\Builder|Student wherePassword($value)
 * @mixin \Eloquent
 */
class Student extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $table = 'students';
    protected $fillable = [
        'nisn', 'nis', 'name', 'address', 'phone_number', 'class_id', 'password'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'password' => 'hashed',
    ];

    public function studentClass() {
        return $this->hasOne(SchoolClass::class, 'id', 'class_id');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StudentRequest;
use App\Models\SchoolClass;
use App\Models\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $students = Student::all();
        return view('pages.students.index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $classes = SchoolClass::all(['id', 'name']);
        return view('pages.students.create', compact('classes'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StudentRequest $request)
    {
        Student::create($request->validated());
        return redirect()->route('students.index')->with('success', 'Student created successfully');
    }

    /**
     * Display the specified resource.
     */
    public function show(Student $student)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Student $student)
    {
        $classes = SchoolClass::all(['id', 'name']);
        return view('pages.students.edit', compact('student', 'classes'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(StudentRequest $request, Student $student)
    {
        $student->update($request->validated());
        return redirect()->route('students.index')->with('success', 'Student updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Student $student)
    {
        $student->delete();
        return redirect()->route('students.index')->with('success', 'Student deleted successfully');
    }
}

resources/views/pages/students/create.blade.php
@extends('layouts.app')

@section('title', 'Create Student')

@section('content')
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            new SlimSelect({
                select: '#classIdSelect'
            });
        });
    </script>
    <x-container class="py-16">
        <h2 class="font-bold text-3xl">Creating Student</h2>
        <form method="post" class="w-full" action="{{ route('students.store') }}">
            @csrf
            @method('POST')
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">NIS</span>
                </div>
                <input name="nis" type="text" value="{{ old('nis') }}" placeholder="22231777"
                    class="input input-bordered input-md w-full @error('nis')
                        {{ 'input-error' }}
                    @enderror" />
                @error('nis')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">NISN</span>
                </div>
                <input name="nisn" type="text" value="{{ old('nisn') }}" placeholder="0000112233"
                    class="input input-bordered input-md w-full @error('nisn')
                        {{ 'input-error' }}
                    @enderror" />
                @error('nisn')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Student Name</span>
                </div>
                <input name="name" type="text" value="{{ old('name') }}" placeholder="Raiden Kunikuzushi"
                    class="input input-bordered input-md w-full @error('name')
                        {{ 'input-error' }}
                    @enderror" />
                @error('name')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>
            <label class="form-control w-full h-28">
                <div class="label">
                    <span class="label-text">Address</span>
                </div>
                <textarea name="address" placeholder="Jl. Kembang Sepatu"
                    class="resize-none h-full textarea textarea-bordered input-md w-full @error('address')
                        {{ 'textarea-error' }}
                    @enderror">{{ old('address') }}</textarea>
                @error('address')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Phone Number</span>
                </div>
                <input name="phone_number" type="text" value="{{ old('phone_number') }}" placeholder="628123456789"
                    class="input input-bordered input-md w-full @error('phone_number')
                        {{ 'input-error' }}
                    @enderror" />
                @error('phone_number')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>
            <label class="form-control w-full">
                <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Enrolled Class</span>
                </div>
                <select id="classIdSelect" name="class_id" class="py-3 rounded-lg px-3 w-full @error('class_id')
                {{ 'input-error' }} @enderror" id="select-beast" placeholder="Select the enrolled class" autocomplete="off">
                    <option value="" selected disabled>Select the enrolled class</option>
                    @foreach ($classes as $class)
                        <option value="{{ $class->id }}">
                            {{ $class->name }}
                        </option>
                    @endforeach
                </select>
                @error('class_id')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>

            <button type="submit" class="btn btn-primary w-full mt-4">Submit</button>
        </form>
    </x-container>
@endsection

resources/views/pages/students/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Student')

@section('content')
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            new SlimSelect({
                select: '#classIdSelect'
            });
        });
    </script>
    <x-container class="py-16">
        <h2 class="font-bold text-3xl">Editing {{ $student->name }}</h2>
        <form method="post" class="w-full" action="{{ route('students.update', $student->id) }}">
            @csrf
            @method('PATCH')
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">NIS</span>
                </div>
                <input name="nis" type="text" value="{{ old('nis') ?? $student->nis }}" placeholder="22231777"
                    class="input input-bordered input-md w-full @error('nis')
                        {{ 'input-error' }}
                    @enderror" />
                @error('nis')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">NISN</span>
                </div>
                <input name="nisn" type="text" value="{{ old('nisn') ?? $student->nisn }}" placeholder="0000112233"
                    class="input input-bordered input-md w-full @error('nisn')
                        {{ 'input-error' }}
                    @enderror" />
                @error('nisn')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Student Name</span>
                </div>
                <input name="name" type="text" value="{{ old('name') ?? $student->name }}" placeholder="Raiden Kunikuzushi"
                    class="input input-bordered input-md w-full @error('name')
                        {{ 'input-error' }}
                    @enderror" />
                @error('name')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>
            <label class="form-control w-full h-28">
                <div class="label">
                    <span class="label-text">Address</span>
                </div>
                <textarea name="address" placeholder="Jl. Kembang Sepatu"
                    class="resize-none h-full textarea textarea-bordered input-md w-full @error('address')
                        {{ 'textarea-error' }}
                    @enderror">{{ old('address') ?? $student->address }}</textarea>
                @error('address')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Phone Number</span>
                </div>
                <input name="phone_number" type="text" value="{{ old('phone_number') ?? $student->phone_number }}" placeholder="628123456789"
                    class="input input-bordered input-md w-full @error('phone_number')
                        {{ 'input-error' }}
                    @enderror" />
                @error('phone_number')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>
            <label class="form-control w-full">
                <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Enrolled Class</span>
                </div>
                <select id="classIdSelect" name="class_id" class="py-3 rounded-lg px-3 w-full @error('class_id')
                {{ 'input-error' }} @enderror" id="select-beast" placeholder="Select the enrolled class" autocomplete="off">
                    <option value="" selected disabled>Select the enrolled class</option>
                    @foreach ($classes as $class)
                        <option value="{{ $class->id }}" {{ $student->class_id == $class->id ? 'selected' : '' }}>
                            {{ $class->name }}
                        </option>
                    @endforeach
                </select>
                @error('class_id')
                    <div class="label">
                        <span class="label-text-alt text-red-300">{{ $message }}</span>
                    </div>
                @enderror
            </label>

            <button type="submit" class="btn btn-primary w-full mt-4">Submit</button>
        </form>
    </x-container>
@endsection

resources/views/pages/students/index.blade.php
@extends('layouts.app')

@section('title', 'School Students')

@section('content')
    <x-container class="py-16 space-y-4">
        <h1 class="text-3xl font-bold">Manage Students</h1>
        @if ($message = Session::get('success'))
            <div id="alertSession" role="alert" class="alert alert-success py-1">
                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none"
                    viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <span>{{ $message }}</span>
                <button class="btn btn-ghost rounded-full" onclick="document.getElementById('alertSession').remove()">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-x" width="16"
                        height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none"
                        stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                        <path d="M18 6l-12 12" />
                        <path d="M6 6l12 12" />
                    </svg></button>
            </div>
        @endif
        <div>
            <div class="w-full flex items-end">
                <a href="{{ route('students.create') }}" class="ml-auto btn btn-sm btn-primary"><svg xmlns="http://www.w3.org/2000/svg"
                        class="icon icon-tabler icon-tabler-plus" width="14" height="14" viewBox="0 0 24 24"
                        stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                        <path d="M12 5l0 14" />
                        <path d="M5 12l14 0" />
                    </svg> New</a>
            </div>
            <div class="overflow-x-auto pb-8">
                <table class="table table-zebra">
                    <!-- head -->
                    <thead>
                        <tr class="text-center">
                            <th>No</th>
                            <th>NIS</th>
                            <th>NISN</th>
                            <th>Name</th>
                            <th>Enrolled Class</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $index = 0;
                        @endphp
                        @forelse ($students as $student)
                            <tr class="text-center">
                                <th>{{ $index + 1 }}</th>
                                <td>{{ $student->nis }}</td>
                                <td>{{ $student->nisn }}</td>
                                <td>{{ $student->name }}</td>
                                <td>{{ $student->studentClass()->first()->name }}</td>
                                <td>
                                    <form method="post" action="{{ route('students.destroy', $student->id) }}">
                                        @csrf
                                        @method('DELETE')
                                        <a role="button" href="{{ route('students.show', $student->id) }}"
                                            class="btn btn-sm btn-primary">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-eye" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                                <path d="M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" />
                                                <path d="M21 12c-2.4 4 -5.4 6 -9 6c-3.6 0 -6.6 -2 -9 -6c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6" />
                                            </svg>
                                        </a>
                                        <a role="button" href="{{ route('students.edit', $student->id) }}"
                                            class="btn btn-sm btn-secondary">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-edit"
                                                width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5"
                                                stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                <path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1" />
                                                <path
                                                    d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z" />
                                                <path d="M16 5l3 3" />
                                            </svg>
                                        </a>
                                        <button type="submit" class="btn btn-sm btn-error">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash"
                                                width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5"
                                                stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                <path d="M4 7l16 0" />
                                                <path d="M10 11l0 6" />
                                                <path d="M14 11l0 6" />
                                                <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
                                                <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                                            </svg>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @php
                                $index++;
                            @endphp
                        @empty
                            <td colspan="6" class="text-center font-semibold text-lg py-4">No Data</td>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </x-container>
@endsection